# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: DotNetCoreCLI@2
  displayName: 'Restore Project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'


- task: DotNetCoreCLI@2
  displayName: 'Publish project'
  inputs:
   command: 'publish'
   arguments:  '--no-build --configuration Release --output $(Build.ArtifactStagingDirectory)/Release'
   projects: '**/*.csproj'
   publishWebProjects: false
   zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  condition: succeeded()
- task: AzureRmWebAppDeployment@2
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'SampleDotNetCoreServiceCon'
    appType: webAppLinux
    WebAppName: 'DemoAzureProjectPipeline'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'